USE CUA_HANG_HOA
--Procedure dùng để đăng nhập
CREATE PROCEDURE dang_nhap @tai_khoan VARCHAR(20), @mat_khau VARCHAR(50)
AS
BEGIN TRANSACTION
	DECLARE @loai_tk CHAR(2);
	SET @loai_tk = NULL;
	--Lấy ra loại tài khoản
	SET @loai_tk = (SELECT TOP 1 tk.LOAI_TK
					FROM TAI_KHOAN tk
					WHERE tk.TEN_TK = @tai_khoan AND tk.MAT_KHAU = @mat_khau AND tk.TRANG_THAI_KHOA = 0)
	IF @loai_tk IS NOT NULL
		BEGIN
			
			IF @loai_tk = 'KH'
				BEGIN
					SELECT @loai_tk AS 'loai_tk', kh.MA_KH AS 'ma' FROM KHACH_HANG kh WHERE kh.TEN_TK_KH = @tai_khoan;
					COMMIT TRAN;
					RETURN;
				END
			ELSE IF @loai_tk = 'QT'
				BEGIN
					SELECT @loai_tk AS 'loai_tk', qt.MA_QT AS 'ma' FROM QUAN_TRI qt WHERE qt.TEN_TK_QT = @tai_khoan;
					COMMIT TRAN;
					RETURN;
				END
			ELSE IF @loai_tk = 'QL'
				BEGIN
					SELECT @loai_tk AS 'loai_tk', ql.MA_QL AS 'ma' FROM QUAN_LI ql WHERE ql.TEN_TK_QL = @tai_khoan;
					COMMIT TRAN;
					RETURN
				END
		END
COMMIT TRANSACTION
GO

--Cấp quyền cho tài khoản đăng nhập
GO
EXEC SP_ADDLOGIN 'DANGNHAP','DANGNHAP','CUA_HANG_HOA';
CREATE USER DANGNHAP FOR LOGIN DANGNHAP;
GRANT SELECT ON TAI_KHOAN TO DANGNHAP;
GRANT SELECT ON NHAN_VIEN TO DANGNHAP;
GRANT SELECT ON QUAN_LI TO DANGNHAP;
GRANT SELECT ON KHACH_HANG TO DANGNHAP;
GRANT SELECT ON QUAN_TRI TO DANGNHAP;
GRANT EXECUTE ON OBJECT::dbo.dang_nhap TO DANGNHAP;

--Cấp quuyền cho role nhân viên
GO
EXEC SP_ADDLOGIN 'NHANVIEN1','NHANVIEN1','CUA_HANG_HOA';
CREATE USER NHANVIEN1 FOR LOGIN NHANVIEN1;
EXEC SP_ADDROLE 'NHANVIEN';
EXEC SP_ADDROLEMEMBER 'NHANVIEN','NHANVIEN1';
GRANT SELECT, UPDATE ON NHAN_VIEN TO NHANVIEN;
GRANT SELECT ON LICH_SU_LUONG TO NHANVIEN;
GRANT SELECT,INSERT ON CHI_TIET_NGAY_LAM TO NHANVIEN;
GRANT EXECUTE ON dbo.nv_diem_danh TO NHANVIEN
GRANT EXECUTE ON dbo.so_luong_don_hang TO NHANVIEN
GRANT EXECUTE ON dbo.doanh_so_nhan_vien TO NHANVIEN
GRANT EXECUTE ON dbo.lich_su_luong TO NHANVIEN

--Cấp quyền cho role quản trị
GO
EXEC SP_ADDLOGIN 'QUANTRI1','QUANTRI1','CUA_HANG_HOA';
CREATE USER QUANTRI1 FOR LOGIN QUANTRI1;
EXEC SP_ADDROLE 'QUANTRI';
EXEC SP_ADDROLEMEMBER 'QUANTRI','QUANTRI1';
GRANT SELECT, UPDATE ON PHIEU_NHAP TO QUANTRI;
GRANT SELECT, UPDATE ON CT_PHIEU_NHAP TO QUANTRI;
GRANT SELECT, UPDATE ON PHIEU_XUAT TO QUANTRI;
GRANT SELECT, UPDATE ON CT_PHIEU_XUAT TO QUANTRI;
GRANT SELECT ON KHO_HANG TO QUANTRI;
GRANT SELECT ON CHI_TIET_KHO TO QUANTRI;
GRANT EXECUTE ON dbo.them_san_pham TO QUANTRI
GRANT EXECUTE ON dbo.cap_nhat_san_pham TO QUANTRI
GRANT EXECUTE ON dbo.xem_lich_su_nhap_hang TO QUANTRI
GRANT EXECUTE ON dbo.xem_lich_su_xuat_hang TO QUANTRI
GRANT EXECUTE ON dbo.quan_li_ton_kho TO QUANTRI

--Cấp quyền cho role quản lí
GO
EXEC SP_ADDLOGIN 'QUANLI1','QUANLI1','CUA_HANG_HOA';
CREATE USER QUANLI1 FOR LOGIN NHANVIEN1;
EXEC SP_ADDROLE 'QUANLI';
EXEC SP_ADDROLEMEMBER 'QUANLI','QUANLI1';
GRANT SELECT, UPDATE,INSERT,DELETE ON NHAN_VIEN TO QUANLI;
GRANT SELECT,UPDATE ON LICH_SU_LUONG TO QUANLI;
GRANT SELECT,UPDATE ON CHI_TIET_NGAY_LAM TO QUANLI;
GRANT SELECT,UPDATE ON SHOP TO QUANLI;
GRANT SELECT,UPDATE ON SP_SHOP TO QUANLI;
GRANT EXECUTE ON dbo.thong_ke_so_luong TO QUANLI

--Cấp quyền cho role khách hàng
GO
EXEC SP_ADDLOGIN 'KHACHHANG1','KHACHHANG1','CHUYEN_HANG_ONLINE';
CREATE USER KHACHHANG1 FOR LOGIN KHACHHANG1;
EXEC SP_ADDROLE 'KHACHHANG';
EXEC SP_ADDROLEMEMBER 'KHACHHANG','KHACHHANG1';
GRANT SELECT ON SHOP TO KHACHHANG;
GRANT SELECT ON SP_SHOP TO KHACHHANG;
GRANT SELECT ON SAN_PHAM TO KHACHHANG;
GRANT SELECT ON GIO_HANG TO KHACHHANG;
GRANT SELECT, INSERT ON  SP_GIOHANG TO KHACHHANG;
GRANT SELECT, INSERT ON DON_HANG TO KHACHHANG;
GRANT SELECT, UPDATE ON KHACH_HANG TO KHACHHANG;
GRANT EXECUTE ON dbo.khach_hang_xem_san_pham TO KHACHHANG
GRANT EXECUTE ON dbo.khach_hang_xem_lich_su_mua_hang TO KHACHHANG
